apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-01
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: 4-pod-tes.
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
#Always make unique labels,when you will run this yml file, 4th pod won't create due to same labels